# Generated by Django 3.2.25 on 2024-12-29 08:04

import base.utils.validators
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=15)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[base.utils.validators.file_validation], verbose_name='image')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
