# Generated by Django 3.2.25 on 2024-11-07 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_ref',
            field=models.ManyToManyField(blank=True, related_name='_profiles_profile_active_ref_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pending_ref',
            field=models.ManyToManyField(blank=True, related_name='_profiles_profile_pending_ref_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
