# Generated by Django 3.2.25 on 2024-11-07 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20241107_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ref_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
