# Generated by Django 3.2.25 on 2024-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ads', 'Ads')], default='Ads', max_length=50)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
