# Generated by Django 5.1.2 on 2024-10-25 06:46

import base.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('Level 9', 'Level 9'), ('Level 10', 'Level 10'), ('Level 11', 'Level 11')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('earning_per_task', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_slip', models.ImageField(null=True, upload_to='packages', validators=[base.utils.validators.file_validation], verbose_name='image')),
                ('wallet_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('daily_earning', models.IntegerField(default=0)),
                ('days_remaining', models.IntegerField(default=0)),
                ('max_upgrade', models.BooleanField(default=False)),
                ('is_withdrawable', models.BooleanField(default=False)),
                ('layer', models.IntegerField(default=0)),
            ],
        ),
    ]
