# Generated by Django 3.2.25 on 2024-12-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='max_number_of_task',
            field=models.IntegerField(default=0),
        ),
    ]
