# Generated by Django 4.2.17 on 2024-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packages_max_number_of_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='daily_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
