# Generated by Django 4.2.17 on 2024-12-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packages_daily_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='daily_earning',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='packages',
            name='earning_per_task',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
