# Generated by Django 5.1.2 on 2024-10-25 06:46

import base.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('7 Days', '7 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days'), ('120 Days', '120 Days'), ('360 Days', '360 Days'), ('1080 Days', '1080 Days')], max_length=20)),
                ('daily_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('wallet_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=20, null=True)),
                ('days_remaining', models.IntegerField(default=0)),
                ('payment_slip', models.ImageField(null=True, upload_to='investments', validators=[base.utils.validators.file_validation], verbose_name='image')),
                ('price', models.IntegerField()),
                ('level', models.IntegerField(blank=True, default=0)),
                ('is_withdrawable', models.BooleanField(default=False)),
            ],
        ),
    ]
