# Generated by Django 3.2.25 on 2024-11-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
