# Generated by Django 4.2.17 on 2024-12-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_payment_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='duration',
            field=models.CharField(choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days'), ('120 Days', '120 Days'), ('360 Days', '360 Days'), ('1080 Days', '1080 Days')], max_length=20),
        ),
    ]
